### ISSUE TITLE
Python Library Not Found?

### ISSUE THREAD

**Issue by JasonMick** [numat/RASPA2#17]
I'm attempting to compile the code.  I get the following error:

---------------------------------------------------------------------------------------------------------------------------
    gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/src/internal_born.o build/temp.linux-x86_64-2.7/src/framework_born.o build/temp.linux-x86_64-2.7/src/complex.o build/temp.linux-x86_64-2.7/src/minimization_simulation.o build/temp.linux-x86_64-2.7/src/molecule.o build/temp.linux-x86_64-2.7/src/linear_equations.o build/temp.linux-x86_64-2.7/src/simulation.o build/temp.linux-x86_64-2.7/src/utils.o build/temp.linux-x86_64-2.7/src/inter_born.o build/temp.linux-x86_64-2.7/src/thermo_baro_stats.o build/temp.linux-x86_64-2.7/src/movies.o build/temp.linux-x86_64-2.7/src/inter_force.o build/temp.linux-x86_64-2.7/src/molecular_dynamics.o build/temp.linux-x86_64-2.7/src/framework.o build/temp.linux-x86_64-2.7/src/scattering_factors.o build/temp.linux-x86_64-2.7/src/cbmc.o build/temp.linux-x86_64-2.7/src/vector.o build/temp.linux-x86_64-2.7/src/inter_hessian.o build/temp.linux-x86_64-2.7/src/rigid.o build/temp.linux-x86_64-2.7/src/cubic_spline_1d.o build/temp.linux-x86_64-2.7/src/internal_energy.o build/temp.linux-x86_64-2.7/src/main.o build/temp.linux-x86_64-2.7/src/input.o build/temp.linux-x86_64-2.7/src/inter_energy.o build/temp.linux-x86_64-2.7/src/framework_energy.o build/temp.linux-x86_64-2.7/src/charge_equilibration.o build/temp.linux-x86_64-2.7/src/molecule_properties.o build/temp.linux-x86_64-2.7/src/statistics.o build/temp.linux-x86_64-2.7/src/status.o build/temp.linux-x86_64-2.7/src/warnings.o build/temp.linux-x86_64-2.7/src/run.o build/temp.linux-x86_64-2.7/src/internal_hessian.o build/temp.linux-x86_64-2.7/src/spectra.o build/temp.linux-x86_64-2.7/src/minimization.o build/temp.linux-x86_64-2.7/src/potentials.o build/temp.linux-x86_64-2.7/src/framework_force.o build/temp.linux-x86_64-2.7/src/mc_moves.o build/temp.linux-x86_64-2.7/src/spacegroup.o build/temp.linux-x86_64-2.7/src/ewald.o build/temp.linux-x86_64-2.7/src/integrate.o build/temp.linux-x86_64-2.7/src/grids.o build/temp.linux-x86_64-2.7/src/internal_force.o build/temp.linux-x86_64-2.7/src/numerical.o build/temp.linux-x86_64-2.7/src/matrix.o build/temp.linux-x86_64-2.7/src/recrossing.o build/temp.linux-x86_64-2.7/src/equations_of_state.o build/temp.linux-x86_64-2.7/src/output.o build/temp.linux-x86_64-2.7/src/monte_carlo.o build/temp.linux-x86_64-2.7/src/integration.o build/temp.linux-x86_64-2.7/src/sample.o build/temp.linux-x86_64-2.7/src/framework_hessian.o build/temp.linux-x86_64-2.7/src/constants.o -L/usr/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/RASPA2/simulations/lib/libraspa2.so
    /bin/ld: cannot find -lpython2.7
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
---------------------------------------------------------------------------------------------------------------------------

The error is strange as /usr/lib/ has the supposedly missing library python2.7 and /usr/lib is included in LD_LIBRARY_PATH.  Not sure why the installation script might not be picking it up.... the bizarre part is the python2.7 lib module was used to retrieve the installer, so earlier in the installation chain it was clearly aware of the library.

I attempted to install with the command "pip install RASPA2", as directed in the README.

My distribution is : CentOS Linux release 7.1.150

**Comment by patrickfuller** [comment]
I just tested the pip install on Ubuntu 15.04 / python 2.7, and it worked on my environment. I don't imagine the CentOS/Debian difference to be a factor, and [RASPA's setup.py](https://github.com/numat/RASPA2/blob/master/setup.py) is fairly vanilla, so I'm guessing it's something to do with your environment.

Are you able to install other compiled python libraries (e.g. does `pip install scipy` work?)

**Comment by JasonMick** [comment]
I may need the python developer libraries as those installers are having issues too and the warning suggests I need the python-devel/python-dev library (the same error is given for numpy, scipy, and matplotlib so definitely some broader issue).  Thanks for the help, I'll update this comment once I get the developer libraries onboard.

**Comment by JasonMick** [comment]
Okay a quick followup -- is there a way to install as non-root (without sudo-er permissions either)??

I'm attempting to install.  But the installer by default appears to demand root level access.  If you can provide installation instructions for non-root users that would be very helpful.  

Also, if you can provide information on how to force the installer to compile with local intel compilers (icpc/icc) that would be helpful as well, as we have those on many of our machines and would like to try to have the code running as fast as possible.  Thank you! :)

**Comment by patrickfuller** [comment]
Read through the [RASPA2 wiki](https://github.com/numat/RASPA2/wiki/For-New-Coders). It explains how to set up a user-level environment with conda that lets you use pip without root access.

**Comment by JasonMick** [comment]
Perfect, thanks!
