### ISSUE TITLE
Simulation is Overriding my Requested Molecule Count

### ISSUE THREAD

**Issue by JasonMick** [numat/RASPA2#18]
I'm attempting to run a basic simulation in NVT ensemble, so I was running:

Basic/MC_Methane_in_Box

When I change the line:

CreateNumberOfMolecules  100

...to:

CreateNumberOfMolecules  128

It still only runs with 100 molecules in the box.  I wasn't able to find any info in the manual explaining this behavior to me.  Can you please explain why it's not using the number I specified?

**Comment by patrickfuller** [comment]
You're going to want to ask David Dubbeldam, who's the author of RASPA. I only maintain the python bindings.

**Comment by JasonMick** [comment]
Got it, I'll email him.  Thank you, Patrick!

**Comment by gregchung** [comment]
This error has do with the fact that the number of methane that can fit inside the simulation box is 100 with the default box size specified in simulation.input file (30 Å x 30 Å x 30 Å). If you increase the length of box up to 35 Å, you will be able to run the simulation.
