### ISSUE TITLE
MakeGrid issue of N2

### ISSUE THREAD

**Issue by headhuanglan** [numat/RASPA2#26]
The N_n2 atom type VDW can be grid correctly. But I can not get the Ewald grid. The program will stop without any error. 
I chekced the 'grid.c'  code, but I can not figure out why the program halts. 

Is there a N2 grid example  available ?

**Comment by headhuanglan** [comment]
problem solved. There is not enough memory to allocate the grid. 
If the author could add some warning to this situation, it could be better.


  // Allocate the memory for this grid
  CoulombGrid=(float****)calloc(NumberOfCoulombGridPoints.x+1,sizeof(float***));
  for(i=0;i<=NumberOfCoulombGridPoints.x;i++)
  {
    CoulombGrid[i]=(float***)calloc(NumberOfCoulombGridPoints.y+1,sizeof(float**));
    for(j=0;j<=NumberOfCoulombGridPoints.y;j++)
    {
      CoulombGrid[i][j]=(float**)calloc(NumberOfCoulombGridPoints.z+1,sizeof(float*));
      for(k=0;k<=NumberOfCoulombGridPoints.z;k++)
        CoulombGrid[i][j][k]=(float*)calloc(8,sizeof(float));
    }
  }

**Comment by patrickfuller** [comment]
This repo is a mirror. I'd recommend emailing the author (David Dubbeldam) directly to add in some warning logic.

**Comment by chdashtyj** [comment]
Hello there, I encounter the same problem when compute C2H6 Ewald grid. The program just gave "killed" word and finished. So if this is a problem about memory insufficient, and how can I solve this problem 
thank you.
