### ISSUE TITLE
RASPA and electric fields

### ISSUE THREAD

**Issue by pufopc** [numat/RASPA2#28]
Hi,
I'm trying to do a simulation in which the adsorbate is polarized and there is an external electric field acting on it. Is this implemented in RASPA? If not, where do you need to modify the code to do that?

**Comment by patrickfuller** [comment]
I'd recommend emailing David Dubbeldam, who's the author of this library.

**Comment by pufopc** [comment]
Thanks, I followed the advise and contacted him.
